"""copy le fichier credentials.py et fill les vrais mdps."""
SUDO_PASSWORD = "changeme"
DB_USER = "psmm"
DB_PASSWORD = "changeme"
MAIL_USER = "slm.psmm67@gmail.com"
MAIL_PASSWORD = "itfa gftj scdu lvhl"
ALCASAR_USER = "identifiant"
ALCASAR_PASSWORD = "changeme"
